# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Akash\Desktop\AI Doctor\AI_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1981, 1081))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1980, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg/img/images.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(390, 680, 1121, 391))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/bg/img/c3a8c07e7ad5f971cb146816a554c8a1.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 420, 641, 271))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/img/449817808physics-electric-curr-unscreen.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(1320, 410, 661, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/img/img/449817808physics-electric-curr-unscreen.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.exitB = QtWidgets.QPushButton(self.frame)
        self.exitB.setGeometry(QtCore.QRect(1700, 990, 221, 81))
        self.exitB.setStyleSheet("background-image: url(:/bg/img/exit - Copy.png);")
        self.exitB.setText("")
        self.exitB.setObjectName("exitB")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(1520, 0, 411, 181))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/img/img/a4c5836f189b2f92dd746e0ccf7037da.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(1530, 0, 381, 178))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(69)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_7.setIndent(-2)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(320, 629, 1281, 451))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/img/img/c3a8c07e7ad5f971cb146816a554c8a1.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(360, 220, 1241, 691))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/img/giphy-5-unscreen.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Gideon"))
import res_rc
